# Use an official Node.js runtime as a parent image
FROM node:19.9-alpine

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

# Install the dependencies
RUN npm install

# Copy the remaining app files to the container
COPY . ./

# Build the app
RUN npm run build

# Set the environment variable to serve the build files
ENV NODE_ENV=production

# Expose port 80
EXPOSE 3000

# Start the app
CMD [ "npm", "start" ]
