version: '3'
    
services:
  web:
    build:
      context: to-do-list-app-test
    restart: always
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  backend:
    restart: always
    build:
      context: to-do-list-api/TodoAPI/TodoAPI
    environment:
      ASPNETCORE_URLS: http://*:5170
    ports:
      - "5170:5170"